### PR TITLE
only delete namespace if no workspaces left

### PR DESCRIPTION
**Pull request by jlangstone-tpzuk**
https://telespazio-uk.atlassian.net/browse/EODHP-928

See ticket for description..

Adding a check to make sure we only (attempt) to delete the namespace if there are no more `Workspace` CRs. Bug introduced a cascading effect of mass deletion of workspaces as an attempt to delete a single workspace triggered the `TearDown` of the namespace reconciler!

### CODE REVIEW

**Review by sgillies-tpzuk — APPROVED** [review]

**Review by sgillies-tpzuk — COMMENTED** [review]
Can I just check that the workspaces are in "workspaces" namespace, and that the namespace being deleted is the user namespace, "ws-username"? Im not sure how a cascading delete of all workspaces would occur when a user workspace is deleted.

**Comment by jlangstone-tpzuk** [comment]
> Can I just check that the workspaces are in "workspaces" namespace, and that the namespace being deleted is the user namespace, "ws-username"? Im not sure how a cascading delete of all workspaces would occur when a user workspace is deleted.

`k get workspace -A` -> all `Workspace` CRs are in the `workspaces` namespace.

Currently if I make a Delete call, it will trigger all the reconcilers, including the `NamespaceReconciler`. The namespace being deleted will be the the one from the `WorkspaceSpec`, which is `workspaces`. It means EVERY workspace in that namespace will be scheduled for deletion because they are part of that workspace.

**Comment by sgillies-tpzuk** [comment]
> > Can I just check that the workspaces are in "workspaces" namespace, and that the namespace being deleted is the user namespace, "ws-username"? Im not sure how a cascading delete of all workspaces would occur when a user workspace is deleted.
> 
> `k get workspace -A` -> all `Workspace` CRs are in the `workspaces` namespace.
> 
> Currently if I make a Delete call, it will trigger all the reconcilers, including the `NamespaceReconciler`. The namespace being deleted will be the the one from the `WorkspaceSpec`, which is `workspaces`. It means EVERY workspace in that namespace will be scheduled for deletion because they are part of that same namespace.

The workspace spec namespace shouldnt have any workspaces in it, so I'm not sure what this is achieving. Unless there's a more subtle bug?

```
spec:
  namespace: ws-jlangstone-2dtpzuk
```

This should be the namespace to be deleted for your workspace. Your actual workspace CR lives in the `workspaces` namespace. The `workspaces` namespace should never be deleted by the operator. Looking at the code, i don't see how the `workspaces` namespace could be deleted by the controller unless someone has set their spec.Namespace value to `workspaces`. I've checked all the workspaces and none have, so im confused as to how that namespace has been triggered to delete.

**Comment by jlangstone-tpzuk** [comment]
I did a hard reset to `988a443b037dfc1da02c5a041c96377317e76318`, the latest stable commit. Deleting branch.

**Pull request merged**
